# Generated by Django 3.1.7 on 2021-03-10 10:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedSong',
            fields=[
                ('song_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('song_name', models.TextField()),
                ('artists', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_songs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=22), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MoodPlaylist',
            fields=[
                ('playlist_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodyapi.user')),
            ],
        ),
    ]
